# Generated by Django 3.0.4 on 2020-03-31 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='signup',
            new_name='email',
        ),
    ]
